/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Paula e Weden
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAgenda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jScrollCampText = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonAgendar = new javax.swing.JButton();
        jLabelData = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jTextValor = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jTextData = new javax.swing.JTextField();
        jComboBoxCliente = new javax.swing.JComboBox<>();
        jComboBoxServico = new javax.swing.JComboBox<>();
        jLabelServico = new javax.swing.JLabel();
        jLabelValor = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelPainel = new javax.swing.JLabel();
        jLabelAgFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAgenda.setBackground(java.awt.Color.lightGray);
        jLabelAgenda.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        jLabelAgenda.setForeground(java.awt.Color.lightGray);
        jLabelAgenda.setText("AGENDA");
        getContentPane().add(jLabelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jTable.setAutoCreateRowSorter(true);
        jTable.setBackground(new java.awt.Color(57, 57, 57));
        jTable.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(255, 102, 0)));
        jTable.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 14)); // NOI18N
        jTable.setForeground(java.awt.Color.lightGray);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Théo", "Cabelo", "10", "18/04/2019", "12:44", null},
                {"2", "Weden", "Barba", "20", "18/04/2019", "13:30", null},
                {"3", "Pedro", "Barba", "20", "18/04/2019", "14:00", null},
                {"4", "Rogério", "Cabelo+Barba", "30", "18/04/2019", "15:00", "Pode ser Antes"},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Serviço", "Valor", "Data", "Hora", "Observação"
            }
        ));
        jTable.setCellSelectionEnabled(true);
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable.setGridColor(new java.awt.Color(255, 102, 0));
        jTable.setName(""); // NOI18N
        jTable.setSelectionForeground(java.awt.Color.white);
        jTable.setSurrendersFocusOnKeystroke(true);
        jScrollPane1.setViewportView(jTable);
        jTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, 960, 240));

        jTextArea1.setBackground(java.awt.Color.darkGray);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jTextArea1.setForeground(java.awt.Color.lightGray);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextArea1.setCaretColor(java.awt.Color.lightGray);
        jTextArea1.setSelectedTextColor(new java.awt.Color(255, 102, 0));
        jTextArea1.setSelectionColor(new java.awt.Color(255, 102, 0));
        jScrollCampText.setViewportView(jTextArea1);

        getContentPane().add(jScrollCampText, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 670, 360));

        jButtonAgendar.setBackground(java.awt.Color.darkGray);
        jButtonAgendar.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jButtonAgendar.setForeground(new java.awt.Color(255, 102, 51));
        jButtonAgendar.setText("AGENDAR");
        jButtonAgendar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 102, 0)));
        jButtonAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 560, 670, 40));

        jLabelData.setBackground(java.awt.Color.lightGray);
        jLabelData.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelData.setForeground(java.awt.Color.lightGray);
        jLabelData.setText("Data");
        getContentPane().add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 40, -1));

        jLabelHora.setBackground(java.awt.Color.lightGray);
        jLabelHora.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelHora.setForeground(java.awt.Color.lightGray);
        jLabelHora.setText("Hora");
        getContentPane().add(jLabelHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 520, -1, -1));

        jTextID.setBackground(java.awt.Color.darkGray);
        jTextID.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jTextID.setForeground(java.awt.Color.lightGray);
        jTextID.setText(" ");
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });
        getContentPane().add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 210, 40));

        jTextValor.setBackground(java.awt.Color.darkGray);
        jTextValor.setFont(new java.awt.Font("Nirmala UI", 0, 12)); // NOI18N
        jTextValor.setForeground(java.awt.Color.lightGray);
        jTextValor.setText(" ");
        jTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 210, 40));

        jTextHora.setBackground(java.awt.Color.darkGray);
        jTextHora.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jTextHora.setForeground(java.awt.Color.lightGray);
        jTextHora.setText(" ");
        jTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 210, 40));

        jTextData.setBackground(java.awt.Color.darkGray);
        jTextData.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 12)); // NOI18N
        jTextData.setForeground(java.awt.Color.lightGray);
        jTextData.setText(" ");
        jTextData.setDisabledTextColor(new java.awt.Color(255, 102, 0));
        jTextData.setDoubleBuffered(true);
        jTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDataActionPerformed(evt);
            }
        });
        getContentPane().add(jTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 210, 40));

        jComboBoxCliente.setBackground(java.awt.Color.darkGray);
        jComboBoxCliente.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jComboBoxCliente.setForeground(java.awt.Color.lightGray);
        jComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Théo", "Weden", "Pedro", "Rogério", " " }));
        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 210, 30));

        jComboBoxServico.setBackground(java.awt.Color.darkGray);
        jComboBoxServico.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 14)); // NOI18N
        jComboBoxServico.setForeground(java.awt.Color.lightGray);
        jComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Barba", "Cabelo", "Sobrancelhas" }));
        jComboBoxServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 336, 210, 30));

        jLabelServico.setBackground(java.awt.Color.lightGray);
        jLabelServico.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelServico.setForeground(java.awt.Color.lightGray);
        jLabelServico.setText("Serviço");
        getContentPane().add(jLabelServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        jLabelValor.setBackground(java.awt.Color.lightGray);
        jLabelValor.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelValor.setForeground(java.awt.Color.lightGray);
        jLabelValor.setText("Valor R$");
        getContentPane().add(jLabelValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 90, -1));

        jLabelID.setBackground(java.awt.Color.lightGray);
        jLabelID.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelID.setForeground(java.awt.Color.lightGray);
        jLabelID.setText("Id");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        jLabelNome.setBackground(java.awt.Color.lightGray);
        jLabelNome.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jLabelNome.setForeground(java.awt.Color.lightGray);
        jLabelNome.setText("Cliente ");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        jLabelPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 930));

        jLabelAgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelAgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1300, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAgendarActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorActionPerformed

    private void jTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextHoraActionPerformed

    private void jTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDataActionPerformed

    private void jComboBoxServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicoActionPerformed

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgendar;
    private javax.swing.JComboBox<String> jComboBoxCliente;
    private javax.swing.JComboBox<String> jComboBoxServico;
    private javax.swing.JLabel jLabelAgFundo;
    private javax.swing.JLabel jLabelAgenda;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPainel;
    private javax.swing.JLabel jLabelServico;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JScrollPane jScrollCampText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextData;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
